image: Visual Studio 2017
branches:
  only:
  - master

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

before_build:
- nuget restore
- nuget install OpenCover -OutputDirectory packages -Version 4.6.519
- choco install codecov

build:
  project: CheckoutPaymentGateway.sln
  verbosity: minimal

test_script:
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full .\PaymentGateway.Service.Tests\PaymentGateway.Service.Tests.csproj" -output:"coverage.xml" -filter:"+[PaymentGateway*]* -[*.Tests]*" -oldstyle
- codecov -f "coverage.xml"
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full .\PaymentGateway.Service.Tests\PaymentGateway.WebApi.Service.Tests.csproj" -output:"api_coverage.xml" -filter:"+[PaymentGateway*]* -[*.Tests]*" -oldstyle
- codecov -f "api_coverage.xml"
