image: Visual Studio 2017
branches:
  only:
  - master

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

before_build:
- nuget restore
- nuget install OpenCover -OutputDirectory packages -Version 4.6.519
- choco install codecov
- choco install "sonarscanner-msbuild-net46" -y

build_script:
 - SonarScanner.MSBuild.exe begin /k:"checkout.com-payment-gateway" /d:"sonar.host.url=https://sonarcloud.io" /o:"dev-11" /d:"sonar.login=130d2a5a5117e7dda2e7c9dfd233c32412c2884d" /d:sonar.cs.opencover.reportsPaths="coverage.xml,api_coverage.xml"
 - msbuild /verbosity:quiet "CheckoutPaymentGateway.sln"
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=results.trx /p:DebugType=full .\PaymentGateway.Service.Tests\PaymentGateway.Service.Tests.csproj" -output:"coverage.xml" -filter:"+[PaymentGateway*]* -[*.Tests]*" -oldstyle
 - codecov -f "coverage.xml"
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --logger:trx;LogFileName=api_results.trx /p:DebugType=full .\PaymentGateway.WebApi.Tests\PaymentGateway.WebApi.Tests.csproj" -output:"api_coverage.xml" -filter:"+[PaymentGateway*]* -[*.Tests]*" -oldstyle
 - codecov -f "api_coverage.xml"
 - SonarScanner.MSBuild.exe end /d:"sonar.login=130d2a5a5117e7dda2e7c9dfd233c32412c2884d"


